# Generated by Django 3.2.4 on 2021-06-12 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_alter_lottery_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='post_text',
        ),
        migrations.AddField(
            model_name='lottery',
            name='hash_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lottery',
            name='pic_pos',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lottery',
            name='tag_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lottery',
            name='pic_url',
            field=models.URLField(max_length=500),
        ),
    ]
